name: Continuous Integration

on:
  push:
    tags: ['*']
    branches: ['main']
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Scala
        uses: coursier/cache-action@v6
      - name: Setup Scala
        uses: coursier/setup-action@v1
        with:
          jvm: temurin:17
      - name: Setup Verilator via Conda
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: verilator-env
          create-args: >-
            verilator=5.028
            -c conda-forge
          cache-environment: true
          init-shell: bash
      - name: mill Test
        run: ./mill _.test
